# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default

steps:
- script: |
    whoami
    id
    ls -l /var/run/docker.sock
  displayName: "Check user and Docker socket permissions"
- task: Maven@4
  displayName: 'Run Maven unit tests'
  inputs:
    mavenPomFile: 'cesizen-simon/backend/pom.xml'
    goals: 'clean verify'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    codeCoverageToolOption: 'JaCoCo'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    isJacocoCoverageReportXML: true
    sqMavenPluginVersionChoice: 'latest'
- task: Docker@2
  displayName: 'Build and push backend'
  inputs:
    command: 'buildAndPush'
    Dockerfile: 'cesizen-simon/backend/Dockerfile'