# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default

variables:
  appName: 'dev-cesizen-backend'
  resourceGroup: 'cesi-bloc'

steps:
- task: Maven@4
  displayName: 'Run Maven unit tests'
  inputs:
    mavenPomFile: 'cesizen-simon/backend/pom.xml'
    goals: 'clean verify'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    codeCoverageToolOption: 'JaCoCo'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    isJacocoCoverageReportXML: true
    sqMavenPluginVersionChoice: 'latest'
# Installer Maven (si nécessaire)
- task: Maven@4
  displayName: 'Build backend Java'
  inputs:
    mavenPomFile: 'cesizen-simon/backend/pom.xml'
    goals: 'clean package -DskipTests'

# Installer Node.js pour frontend
- task: NodeTool@0
  displayName: 'Installer Node.js'
  inputs:
    versionSpec: '16.x'

# Build frontend
- script: |
    cd cesizen-simon/backend/frontend
    npm install
    npm run build
  displayName: 'Build frontend'

# Build backoffice
- script: |
    cd cesizen-simon/backend/backoffice
    npm install
    npm run build
  displayName: 'Build backoffice'

# Préparer le dossier deploy et zipper
- script: |
    mkdir -p deploy
    cp cesizen-simon/backend/target/*.jar deploy/ # adapte l'extension si c'est .war
    cp -r cesizen-simon/backend/frontend/build deploy/frontend-build
    cp -r cesizen-simon/backend/backoffice/build deploy/backoffice-build
    cd deploy
    zip -r ../app-package.zip *
  displayName: 'Préparer et zipper le package'

# Publier l'artifact pour debug (optionnel)
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'app-package.zip'
    ArtifactName: 'drop'

# Déployer sur Azure App Service
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'dev-cesizen-backend-connection'
    appName: $(appName)
    package: '$(System.DefaultWorkingDirectory)/app-package.zip'